# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "return-app"
client_id = "396e2eb8e98ff4462b54764027a86469"
application_url = "https://william-golf-steve-business.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://william-golf-steve-business.trycloudflare.com/auth/callback",
  "https://william-golf-steve-business.trycloudflare.com/auth/shopify/callback",
  "https://william-golf-steve-business.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "return-x-store.myshopify.com"
